"""initial schema

Revision ID: 3685159f7a58
Revises: 
Create Date: 2026-10-10 19:03:33.335039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3685159f7a58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('day')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(length=120), nullable=False),
    sa.Column('actor_role', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.String(length=60), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_at'), 'audit_events', ['at'], unique=False)
    op.create_index(op.f('ix_audit_events_case_id'), 'audit_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_audit_events_target_id'), 'audit_events', ['target_id'], unique=False)
    op.create_table('firms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crd', sa.String(length=20), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('application', sa.JSON(), nullable=False),
    sa.Column('reliance_eligible', sa.Boolean(), nullable=False),
    sa.Column('risk_tier', sa.String(length=10), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firms_crd'), 'firms', ['crd'], unique=True)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.String(length=60), nullable=False),
    sa.Column('subject_name', sa.String(length=200), nullable=False),
    sa.Column('risk_tier', sa.String(length=10), nullable=False),
    sa.Column('next_review', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_on', sa.Date(), nullable=True),
    sa.Column('response_due', sa.Date(), nullable=True),
    sa.Column('trigger', sa.String(length=30), nullable=False),
    sa.Column('restriction_id', sa.Integer(), nullable=True),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_subject_id'), 'reviews', ['subject_id'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('client_key', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('group', sa.String(length=20), nullable=False),
    sa.Column('registration_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('path', sa.String(length=2), nullable=True),
    sa.Column('risk_tier', sa.String(length=10), nullable=True),
    sa.Column('application', sa.JSON(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('change_history', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_client_key'), 'accounts', ['client_key'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=300), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=True),
    sa.Column('client_account_id', sa.String(length=40), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('demo_note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('queue', sa.String(length=40), nullable=True),
    sa.Column('application', sa.JSON(), nullable=False),
    sa.Column('decisions', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('queue_entered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('manual_steps', sa.Integer(), nullable=False),
    sa.Column('nigo_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_account_id'), 'cases', ['account_id'], unique=False)
    op.create_index(op.f('ix_cases_queue'), 'cases', ['queue'], unique=False)
    op.create_index(op.f('ix_cases_target_id'), 'cases', ['target_id'], unique=False)
    op.create_table('role_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=40), nullable=True),
    sa.Column('to_status', sa.String(length=40), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_transitions_case_id'), 'case_transitions', ['case_id'], unique=False)
    op.create_table('pending_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('decision_type', sa.String(length=40), nullable=False),
    sa.Column('value', sa.String(length=40), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('proposed_by', sa.Integer(), nullable=False),
    sa.Column('proposed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['proposed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_decisions_case_id'), 'pending_decisions', ['case_id'], unique=False)
    op.create_table('restrictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.String(length=60), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('placed_by', sa.String(length=120), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('removed_by', sa.String(length=120), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removal_reason', sa.Text(), nullable=True),
    sa.Column('authorization', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restrictions_target_id'), 'restrictions', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restrictions_target_id'), table_name='restrictions')
    op.drop_table('restrictions')
    op.drop_index(op.f('ix_pending_decisions_case_id'), table_name='pending_decisions')
    op.drop_table('pending_decisions')
    op.drop_index(op.f('ix_case_transitions_case_id'), table_name='case_transitions')
    op.drop_table('case_transitions')
    op.drop_table('role_grants')
    op.drop_index(op.f('ix_cases_target_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_queue'), table_name='cases')
    op.drop_index(op.f('ix_cases_account_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_accounts_client_key'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_reviews_subject_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_firms_crd'), table_name='firms')
    op.drop_table('firms')
    op.drop_index(op.f('ix_audit_events_target_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_case_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('ai_usage')
    # ### end Alembic commands ###
